fix: it was updates the .npmrc file so we avoid issue with peerDependencies

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -2,7 +2,7 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 if ! head -1 "$1" | grep -qE "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+?\))?: .{1,}$"; then
-    echo "Aborting commit. Your commit message is invalid." >&2
+    echo "Aborting commit. Your commit message is invalid. Please make usage of 'commit-changes' command." >&2
     exit 1
 fi
 if ! head -1 "$1" | grep -qE "^.{1,93}$"; then
